import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Header from "../components/Header";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Review | In the loop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box bg="gray.100" w="100vw" h="100vh">
            <Header account="xddd" />
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
