import type { Metadata } from "next";
import { Web3Provider } from '../utils/Web3Provider';
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Coal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <Web3Provider>
          <Header />
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
