import type { Metadata } from "next";
import { Web3Provider } from '../utils/Web3Provider';
import { ChakraProvider } from '@chakra-ui/react'
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ChakraProvider>
        <Web3Provider>
          <div className={inter.className}>{children}</div>
        </Web3Provider>
      </ChakraProvider>
    </html>
  );
}
